/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElChecbox: typeof import('element-plus/es')['ElChecbox']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Header: typeof import('./src/components/layout/c-cpn/header.vue')['default']
    HeaderInfo: typeof import('./src/components/layout/components/mainHeader/components/headerInfo.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    LayoutCom: typeof import('./src/components/layout/layoutCom.vue')['default']
    LayoutCpn: typeof import('./src/components/layout/layoutCpn.vue')['default']
    LayoutView: typeof import('./src/components/layout/layoutView.vue')['default']
    LeftMenu: typeof import('./src/components/layout/c-cpn/leftMenu.vue')['default']
    Mainheader: typeof import('./src/components/layout/c-cpn/mainheader.vue')['default']
    MainHeader: typeof import('./src/components/layout/components/mainHeader/mainHeader.vue')['default']
    MainMenu: typeof import('./src/components/layout/components/mainMenu/mainMenu.vue')['default']
    Menu: typeof import('./src/components/Menu/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubMenu: typeof import('./src/components/layout/c-cpn/subMenu.vue')['default']
  }
}
